version: "3.9"

services:
  sql-server:
      image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: P@ssw0rd.123
        ACCEPT_EULA: Y
        MSSQL_PID: Express
      networks:
        - webnet
  evrendev:
    image: evrendev-api
    ports:
      - "3000:80"
      - "3001:443"
    depends_on:
      - sql-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks: 
      - webnet
networks:
  webnet: